/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controle.Cep;
//import Controle.Cep.buscaCep;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansPaciente;
import modeloBeans.ModeloTabela;
import modeloConection.ConexaoDB;
import modeloDao.DaoPaciente;
import net.proteanit.sql.DbUtils;
import modeloBeans.BeansPaciente;

/**
 *
 * @author Denis
 */
public class FormPacientes extends javax.swing.JFrame {

    ConexaoDB conex = new ConexaoDB();
    DaoPaciente control = new DaoPaciente();
    BeansPaciente mod = new BeansPaciente();
    Cep cep = new Cep();
    
   
    
   int flag = 0;
    public FormPacientes() {
        initComponents();
        
         URL caminhoIcone = getClass().getResource("/Imagens/icon.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        
       preencherTabela("select id_paciente, "
               +"nome_paciente, "
               +"nasc_paciente, "
               +"rg_paciente, "
               +"telefone,"
               +"rua_paciente,"
               +"cep_paciente,"
               +"complemento,"
               +"bairro_paciente, "
               +"cpf_paciente, "
               +"numero,"
               +"cidade_paciente, "
               +"estado_paciente, "
               +"celular_paciente from pacientes order by nome_paciente");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldRG = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataNasc1 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jTextFieldComp = new javax.swing.JTextField();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxEstados = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePaciente = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pacientes");
        setName("Cadastro de Pacientes"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Pacientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Nome: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Data Nascimento: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("RG: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("Telefone: ");

        jTextFieldNome.setEnabled(false);
        jTextFieldNome.setOpaque(false);
        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyTyped(evt);
            }
        });

        try {
            jFormattedTextFieldRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRG.setEnabled(false);
        jFormattedTextFieldRG.setOpaque(false);
        jFormattedTextFieldRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldRGActionPerformed(evt);
            }
        });
        jFormattedTextFieldRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldRGKeyTyped(evt);
            }
        });

        try {
            jFormattedTextFieldDataNasc1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataNasc1.setEnabled(false);
        jFormattedTextFieldDataNasc1.setOpaque(false);
        jFormattedTextFieldDataNasc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataNasc1ActionPerformed(evt);
            }
        });
        jFormattedTextFieldDataNasc1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldDataNasc1KeyTyped(evt);
            }
        });

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setEnabled(false);
        jFormattedTextFieldTelefone.setOpaque(false);
        jFormattedTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTelefoneActionPerformed(evt);
            }
        });
        jFormattedTextFieldTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldTelefoneKeyTyped(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setText("Rua: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel8.setText("Cep: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel9.setText("Complemento: ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel10.setText("Bairro: ");

        jTextFieldRua.setEnabled(false);
        jTextFieldRua.setOpaque(false);
        jTextFieldRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRuaKeyTyped(evt);
            }
        });

        jTextFieldComp.setEnabled(false);
        jTextFieldComp.setOpaque(false);
        jTextFieldComp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCompKeyTyped(evt);
            }
        });

        try {
            jFormattedTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCep.setEnabled(false);
        jFormattedTextFieldCep.setOpaque(false);
        jFormattedTextFieldCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCepFocusLost(evt);
            }
        });
        jFormattedTextFieldCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldCepKeyTyped(evt);
            }
        });

        jTextFieldBairro.setEnabled(false);
        jTextFieldBairro.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Estado - UF :");

        jComboBoxEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre (AC)", "Amapá (AP)", "Amazonas (AM)", "Pará (PA)", "Rondônia (RO)", "Roraima (RR)", "Tocantins (TO)", "Paraná (PR)", "Rio Grande do Sul (RS)", "Santa Catarina (SC)", "Alagoas (AL)", "Bahia (BA)", "Ceará (CE)", "Maranhão (MA)", "Paraíba (PB)", "Pernambuco (PE)", "Piauí (PI)", "Rio Grande do Norte (RN)", "Sergipe (SE)", "Espírito Santo (ES)", "Minas Gerais (MG)", "Rio de Janeiro (RJ)", "São Paulo (SP)", "Distrito Federal (DF)", "Goiás (GO)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)" }));
        jComboBoxEstados.setEnabled(false);
        jComboBoxEstados.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Cidade:");

        jTextFieldCidade.setEnabled(false);
        jTextFieldCidade.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Número:");

        jTextFieldNumero.setEnabled(false);
        jTextFieldNumero.setOpaque(false);
        jTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldComp)
                            .addComponent(jComboBoxEstados, 0, 232, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCidade)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumero))
                    .addComponent(jTextFieldRua))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxEstados, jFormattedTextFieldCep, jTextFieldBairro, jTextFieldCidade, jTextFieldComp, jTextFieldNumero, jTextFieldRua});

        jTablePaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePaciente.setOpaque(false);
        jTablePaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePaciente);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setText("ID: ");

        jTextFieldID.setEnabled(false);
        jTextFieldID.setOpaque(false);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1472621632_Accept-Male-User.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1472621627_Edit-Male-User.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1472621652_Remove-Male-User.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1472622028_message-delete.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1472621621_Add-Male-User.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Pesquisar Pacientes");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gnome-Edit-Clear-32.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar Campos");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jTextFieldPesquisa.setOpaque(false);
        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel12.setText("Pesquisa: ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Celular:");

        jFormattedTextFieldCelular.setEnabled(false);
        jFormattedTextFieldCelular.setOpaque(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("CPF:");

        jFormattedTextFieldCpf.setEnabled(false);
        jFormattedTextFieldCpf.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome))
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldDataNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancelar, jButtonEditar, jButtonExcluir, jButtonNovo, jButtonSalvar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jFormattedTextFieldDataNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldID)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonLimpar, jButtonPesquisar, jTextFieldPesquisa});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCancelar, jButtonEditar, jButtonExcluir, jButtonNovo, jButtonSalvar});

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 832, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo_telaprincipal.jpg"))); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 680));

        setSize(new java.awt.Dimension(867, 715));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyTyped
        String caracteres="0987654321";
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPesquisaKeyTyped

    private void jTextFieldPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyReleased
        // Este evento preenche a Tabela em tempo Real

    }//GEN-LAST:event_jTextFieldPesquisaKeyReleased

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldNome.setText("");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldComp.setText("");
        jTextFieldID.setText("");
        jTextFieldPesquisa.setText("");
        jTextFieldRua.setText("");
        jFormattedTextFieldCep.setText("");
        jFormattedTextFieldDataNasc1.setText("");
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        preencherTabela("select * from pacientes order by nome_paciente");
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        if (jTextFieldPesquisa.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Por Favor!\nPreencha o Campo de Pesquisa!");
            jTextFieldPesquisa.requestFocus();
            preencherTabela("select * from pacientes order by nome_paciente");
            jButtonEditar.setEnabled(!true);
            jButtonExcluir.setEnabled(!true);
        }else{

            mod.setPesquisa(jTextFieldPesquisa.getText());
            BeansPaciente model = control.buscaPaciente(mod);

            jTextFieldNome.setText(model.getNome_paciente());
            jFormattedTextFieldDataNasc1.setText(model.getNasc_paciente());
            jFormattedTextFieldTelefone.setText(model.getTelefone());
            jFormattedTextFieldRG.setText(model.getRg());
            jFormattedTextFieldCep.setText(model.getCep());
            jTextFieldRua.setText(model.getRua());
            jTextFieldComp.setText(model.getComplemento());
            jTextFieldID.setText(String.valueOf(model.getId_paciente()));
            jTextFieldBairro.setText(model.getBairro());
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jButtonNovo.setEnabled(false);
            jButtonCancelar.setEnabled(true);
            jTextFieldPesquisa.setText("");

            preencherTabela("select *from pacientes where nome_paciente ilike '%" + mod.getPesquisa()+ "%'");}

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldDataNasc1.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jFormattedTextFieldCep.setEnabled(true);
        jTextFieldComp.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldPesquisa.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
        jButtonLimpar.setEnabled(false);
        jTablePaciente.setVisible(!false);
        jButtonNovo.setEnabled(false);

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        //Campos a serem ocultados/liberados
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldDataNasc1.setEnabled(false);
        jFormattedTextFieldRG.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);
        jTextFieldID.setEnabled(false);
        jTextFieldRua.setEnabled(false);
        jFormattedTextFieldCep.setEnabled(false);
        jTextFieldComp.setEnabled(false);
        jTextFieldPesquisa.setEnabled(true);
        jTextFieldBairro.setEnabled(false);
        //Botões a serem ocultados/liberados
        jButtonNovo.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonPesquisar.setEnabled(true);
        jButtonLimpar.setEnabled(true);
        jTablePaciente.setVisible(true);
        //Campos a serem limpos
        jTextFieldNome.setText("");
        jFormattedTextFieldDataNasc1.setText("");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldID.setText("");
        jTextFieldRua.setText("");
        jFormattedTextFieldCep.setText("");
        jTextFieldComp.setText("");
        jTextFieldPesquisa.setText("");
        //Método de retorno da JTable
        preencherTabela("select * from pacientes order by nome_paciente");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir Registro?");
        if(resposta==JOptionPane.YES_OPTION){
            mod.setId_paciente(Integer.parseInt(jTextFieldID.getText()));
            control.Excluir(mod);
            jButtonExcluir.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jTextFieldNome.setText("");
            jFormattedTextFieldRG.setText("");
            jFormattedTextFieldTelefone.setText("");
            jTextFieldComp.setText("");
            jTextFieldID.setText("");
            jTextFieldPesquisa.setText("");
            jTextFieldRua.setText("");
            jFormattedTextFieldCep.setText("");
            jFormattedTextFieldDataNasc1.setText("");
            jButtonCancelar.setEnabled(false);
            jButtonNovo.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null,"Os Registros não foram Deletados");
            jButtonExcluir.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jTextFieldNome.setText("");
            jFormattedTextFieldRG.setText("");
            jFormattedTextFieldTelefone.setText("");
            jTextFieldComp.setText("");
            jTextFieldID.setText("");
            jTextFieldPesquisa.setText("");
            jTextFieldRua.setText("");
            jFormattedTextFieldCep.setText("");
            jFormattedTextFieldDataNasc1.setText("");

        }
        preencherTabela("select * from pacientes order by nome_paciente");
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2 ;
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldDataNasc1.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jFormattedTextFieldCep.setEnabled(true);
        jTextFieldComp.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldPesquisa.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
        jButtonLimpar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jTablePaciente.setVisible(!false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (jTextFieldNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Por Favor!\nPreencha o Campo Nome!");
            jTextFieldNome.requestFocus();

        }else if (jFormattedTextFieldDataNasc1.getText().equals("  /  /    ")){
            JOptionPane.showMessageDialog(null,"Por Favor!\nPreencha a Data de Nascimento!");
            jFormattedTextFieldDataNasc1.requestFocus();

        }else if(jFormattedTextFieldTelefone.getText().equals("(  )    -    ")){
            JOptionPane.showMessageDialog(null,"Por Favor!\nPreencha Telefone!");
            jFormattedTextFieldTelefone.requestFocus();

        }else if(jFormattedTextFieldRG.getText().equals("        - ")){
            JOptionPane.showMessageDialog(null,"Por Favor!\nPreencha o RG!");
            jFormattedTextFieldRG.requestFocus();

        }else if(jTextFieldRua.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Por Favor!\nPreencha a Rua!");
            jTextFieldRua.requestFocus();

        }else if(jFormattedTextFieldCep.getText().equals("     -   ")){
            JOptionPane.showMessageDialog(null,"Por Favor!\nPreencha o Cep!");
            jFormattedTextFieldCep.requestFocus();
        }else
        if (flag == 1){
            mod.setNome_paciente((String)jTextFieldNome.getText());
            mod.setRg(jFormattedTextFieldRG.getText());
            mod.setTelefone(jFormattedTextFieldTelefone.getText());
            mod.setNasc_paciente(jFormattedTextFieldDataNasc1.getText());
            mod.setRua(jTextFieldRua.getText());
            mod.setBairro(jTextFieldBairro.getText());
            mod.setCep(jFormattedTextFieldCep.getText());
            mod.setComplemento(jTextFieldComp.getText());
            control.Salvar(mod);
            jTextFieldNome.setText("");
            jFormattedTextFieldRG.setText("");
            jFormattedTextFieldTelefone.setText("");
            jTextFieldComp.setText("");
            jTextFieldID.setText("");
            jTextFieldPesquisa.setText("");
            jTextFieldRua.setText("");
            jFormattedTextFieldCep.setText("");
            jFormattedTextFieldDataNasc1.setText("");
            jButtonCancelar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonPesquisar.setEnabled(true);
            jButtonLimpar.setEnabled(true);
            jButtonNovo.setEnabled(true);
            //Campos
            jTextFieldNome.setEnabled(false);
            jFormattedTextFieldDataNasc1.setEnabled(false);
            jFormattedTextFieldRG.setEnabled(false);
            jFormattedTextFieldTelefone.setEnabled(false);
            jTextFieldID.setEnabled(false);
            jTextFieldRua.setEnabled(false);
            jFormattedTextFieldCep.setEnabled(false);
            jTextFieldComp.setEnabled(false);
            jTextFieldPesquisa.setEnabled(true);
            jTextFieldBairro.setEnabled(false);
            preencherTabela("select * from pacientes order by nome_paciente");
        }else{
            mod.setNome_paciente((String)jTextFieldNome.getText());
            mod.setRg(jFormattedTextFieldRG.getText());
            mod.setTelefone(jFormattedTextFieldTelefone.getText());
            mod.setNasc_paciente(jFormattedTextFieldDataNasc1.getText());
            mod.setRua(jTextFieldRua.getText());
            mod.setBairro(jTextFieldBairro.getText());
            mod.setCep(jFormattedTextFieldCep.getText());
            mod.setComplemento(jTextFieldComp.getText());
            mod.setId_paciente(Integer.parseInt(jTextFieldID.getText()));
            control.Editar(mod);
            preencherTabela("select * from pacientes order by nome_paciente");
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTablePacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacienteMouseClicked
        String nome_paciente=""+jTablePaciente.getValueAt(jTablePaciente.getSelectedRow(),1);
        conex.getConnection();
        conex.executaSql("select * from pacientes where nome_paciente='"+ nome_paciente+"'");
        try{
            conex.rs.first();
            jTextFieldID.setText(String.valueOf(conex.rs.getInt("id_paciente")));
            jTextFieldNome.setText(conex.rs.getString("nome_paciente"));
            jFormattedTextFieldDataNasc1.setText(conex.rs.getString("nasc_paciente"));
            jFormattedTextFieldRG.setText(conex.rs.getString("rg_paciente"));
            jFormattedTextFieldTelefone.setText(conex.rs.getString("telefone"));
            jTextFieldRua.setText(conex.rs.getString("rua_paciente"));
            jFormattedTextFieldCep.setText(conex.rs.getString("cep_paciente"));
            jTextFieldComp.setText(conex.rs.getString("complemento"));
            jTextFieldBairro.setText(conex.rs.getString("bairro_paciente"));
            jFormattedTextFieldCpf.setText(conex.rs.getString("cpf_paciente"));
            jTextFieldNumero.setText(String.valueOf(conex.rs.getInt("numero")));
            jTextFieldCidade.setText(conex.rs.getString("cidade_paciente"));
            jComboBoxEstados.setSelectedItem(conex.rs.getString("estado_paciente"));   
            jFormattedTextFieldCelular.setText(conex.rs.getString("celular_paciente"));
            
            jButtonExcluir.setEnabled(true);
            jButtonEditar.setEnabled(true);
            jButtonNovo.setEnabled(false);
            jButtonCancelar.setEnabled(true);
            jTextFieldPesquisa.setEnabled(!false);
            jButtonPesquisar.setEnabled(!false);
            jButtonLimpar.setEnabled(!false);

        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Erro ao Selecionar Dados "+ ex);
        }
        //conex.desconecta();

    }//GEN-LAST:event_jTablePacienteMouseClicked

    private void jTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroActionPerformed

    private void jFormattedTextFieldCepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCepKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextFieldCepKeyTyped

    private void jFormattedTextFieldCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCepFocusLost
        //Aqui será o método para buscar o cep!

        //Cep.endereco.getText(jTextFieldRua.setText(cep));
        
        Cep cep = new Cep();
       jTextFieldRua.setText(cep.getEndereco());
       jTextFieldBairro.setText(cep.getBairro());
       jComboBoxEstados.setSelectedItem(cep.getEstado());
       jTextFieldCidade.setText(cep.getCidade());
       

    }//GEN-LAST:event_jFormattedTextFieldCepFocusLost

    private void jTextFieldCompKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCompKeyTyped
        String caracteres="0987654321";
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCompKeyTyped

    private void jTextFieldRuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRuaKeyTyped

    }//GEN-LAST:event_jTextFieldRuaKeyTyped

    private void jFormattedTextFieldTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefoneKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextFieldTelefoneKeyTyped

    private void jFormattedTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTelefoneActionPerformed

    private void jFormattedTextFieldDataNasc1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataNasc1KeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextFieldDataNasc1KeyTyped

    private void jFormattedTextFieldDataNasc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataNasc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataNasc1ActionPerformed

    private void jFormattedTextFieldRGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldRGKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextFieldRGKeyTyped

    private void jFormattedTextFieldRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldRGActionPerformed

    private void jTextFieldNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyTyped
        String caracteres="0987654321";
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNomeKeyTyped

    public void preencherTabela(String Sql){
    ArrayList dados = new ArrayList();
    String [] colunas;
        colunas = new String[]{"ID","Nome","RG","CPF","Aniversário","Cep","Rua","Nº","Bairro","Estado","Cidade","Telefone","Celular"};
    conex.getConnection();
    conex.executaSql(Sql);
    
    
    try{
    conex.rs.first(); 
    do{
       
        dados.add(new Object[]{
            conex.rs.getInt("id_paciente"),
            conex.rs.getString("nome_paciente"),
            conex.rs.getString("rg_paciente"),
            conex.rs.getString("cpf_paciente"),
            conex.rs.getString("nasc_paciente"),
            conex.rs.getString("cep_paciente"),
            conex.rs.getString("rua_paciente"),
            conex.rs.getInt("numero"),
            conex.rs.getString("bairro_paciente"),
            conex.rs.getString("estado_paciente"),
            conex.rs.getString("cidade_paciente"),
            conex.rs.getString("telefone"),
            conex.rs.getString("celular_paciente"),
            
            
            
        
        });
    }while(conex.rs.next());
    
       
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(null, " Erro ao Procurar na  Lista! \n Por Favor Pesquise novamente!");
        jTextFieldPesquisa.requestFocus();
        jButtonEditar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jTextFieldNome.setText("");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldComp.setText("");
        jTextFieldID.setText("");
        jTextFieldPesquisa.setText("");
        jTextFieldRua.setText("");
        jFormattedTextFieldCep.setText("");
        jFormattedTextFieldDataNasc1.setText(""); 
        preencherTabela("select *from pacientes order by nome_paciente");
        return;
           
    }ModeloTabela modelo = new ModeloTabela(dados,colunas);
    jTablePaciente.setModel(modelo);
    
    jTablePaciente.getColumnModel().getColumn(0).setPreferredWidth(40);
    jTablePaciente.getColumnModel().getColumn(0).setResizable(false);
    jTablePaciente.getColumnModel().getColumn(1).setPreferredWidth(210);
    jTablePaciente.getColumnModel().getColumn(1).setResizable(false);
    jTablePaciente.getColumnModel().getColumn(2).setPreferredWidth(90);
    jTablePaciente.getColumnModel().getColumn(2).setResizable(false);
    jTablePaciente.getColumnModel().getColumn(3).setPreferredWidth(100);
    jTablePaciente.getColumnModel().getColumn(3).setResizable(false);
    jTablePaciente.getColumnModel().getColumn(4).setPreferredWidth(150);
    jTablePaciente.getColumnModel().getColumn(4).setResizable(false);
    jTablePaciente.getColumnModel().getColumn(5).setPreferredWidth(105);
    jTablePaciente.getColumnModel().getColumn(5).setResizable(false);
    jTablePaciente.getColumnModel().getColumn(6).setPreferredWidth(98);
    jTablePaciente.getColumnModel().getColumn(6).setResizable(false);
    jTablePaciente.getColumnModel().getColumn(7).setPreferredWidth(50);
    jTablePaciente.getColumnModel().getColumn(7).setResizable(false);
    jTablePaciente.getColumnModel().getColumn(8).setPreferredWidth(120);
    jTablePaciente.getColumnModel().getColumn(8).setResizable(false);
    jTablePaciente.getColumnModel().getColumn(9).setPreferredWidth(120);
    jTablePaciente.getColumnModel().getColumn(9).setResizable(false);
    jTablePaciente.getColumnModel().getColumn(10).setPreferredWidth(120);
    jTablePaciente.getColumnModel().getColumn(10).setResizable(false);
    jTablePaciente.getColumnModel().getColumn(11).setPreferredWidth(120);
    jTablePaciente.getColumnModel().getColumn(11).setResizable(false);
    
    jTablePaciente.getTableHeader().setReorderingAllowed(false);
    jTablePaciente.setAutoResizeMode(jTablePaciente.AUTO_RESIZE_OFF);
    jTablePaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    //conex.desconecta();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxEstados;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNasc1;
    private javax.swing.JFormattedTextField jFormattedTextFieldRG;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePaciente;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComp;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRua;
    // End of variables declaration//GEN-END:variables
}
