/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Denis
 */
public class Loading extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/Imagens/icon.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        
        
        
        //Todo esse código faz a Barrinha carregar
        new Thread(){
           public void run (){
               for(int i=0; i<101; i++){
                   try {
                       //Tempo de Vida da Thread
                       sleep(120);
                       jProgressBar1.setValue(i);
                       
                       if(jProgressBar1.getValue()<=10){
                           jLabel2.setText("Resolvendo Cache ... ");                           
                       }else if(jProgressBar1.getValue()<=25){
                           jLabel2.setText("Carregando Banco de Dados ... ");
                       }else if(jProgressBar1.getValue()<=40){
                           jLabel2.setText("Carregando Tabelas ... ");
                       }else if(jProgressBar1.getValue()<=50){
                           jLabel2.setText("Carregando Sistema Clínica Médica ... ");
                       }else if(jProgressBar1.getValue()<=70){
                           jLabel2.setText("Finalizando Carregamento  ... ");
                       }else if(jProgressBar1.getValue()<=90){
                           jLabel2.setText("Iniciando Sistema ... ");
                       }else if(jProgressBar1.getValue()== 94){
                           jLabel2.setText("Sistema Carregado com Sucesso ... ");
                       }
                       
                      
                   } catch (InterruptedException ex) {
                       Logger.getLogger(Loading.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }
               //Esse código fecha a tela de carregamento e Abre a Tela de Login
           dispose();
           
             TelaLogin telalogin = new TelaLogin();
                       telalogin.setVisible(true);
           
           } 
            
        }.start();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DG Software Developer carregando os componentes necessários ...");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 320, 400, 20);

        jProgressBar1.setBackground(new java.awt.Color(204, 255, 255));
        jProgressBar1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBar1.setToolTipText("Carregando Componentes do Sistema");
        jProgressBar1.setBorder(null);
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(20, 300, 500, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/deniscartao2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-330, -10, 890, 400);

        setSize(new java.awt.Dimension(554, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    }
    

