package view;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modeloBeans.Hora;
import modeloConection.ConexaoDB;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoDB conex = new ConexaoDB();
    FormMedicos telamedicos = new FormMedicos();
    FormUsuarios telausuarios = new FormUsuarios();
    FormPacientes telapacientes = new FormPacientes();
    FormEnfermeiros telaenfermeiros = new FormEnfermeiros();
    FormAgendamentos telaagenda = new FormAgendamentos();
    FormAgendaDia telaagendadia = new FormAgendaDia();
       
    
     
            
    public TelaPrincipal(String usuario) {
       setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        
        
        
        URL caminhoIcone = getClass().getResource("/Imagens/icon.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        
        jLabelUsuario.setText(usuario);
        conex.getConnection();
        
        //A linha Abaixo exibe a Data Atual do Sistema
        Date data = new Date();
        DateFormat formatadorD = DateFormat.getDateInstance(DateFormat.LONG);
        jLabelDataAtual.setText(formatadorD.format(data));
        
        
       //A linha Abaixo exibe a Hora Atual do Sistema
       Hora mostra_hora = new Hora();
       mostra_hora.ler_hora();
       jLabelHoraAtual.setText("Horário: " + mostra_hora.hora);
             
       timer1.start();
       
       
       //Esse método seta Imagem no nosso Label referente ao DB
       
       if(conex != null){
           jLabelDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dbo.png")));
       }else{
           jLabelDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dbe1.png")));
       }
        }
    
   

    private TelaPrincipal() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jButtonCadPaciente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonCadUsuario = new javax.swing.JButton();
        jButtonCadEnfermeira = new javax.swing.JButton();
        jButtonAgenda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonCadMedicos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelPlanoFundPainel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonExitB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelDataAtual = new javax.swing.JLabel();
        jLabelHoraAtual = new javax.swing.JLabel();
        jLabelDB = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadMed = new javax.swing.JMenuItem();
        jMenuItemCadPac = new javax.swing.JMenuItem();
        jMenuItemCadEnf = new javax.swing.JMenuItem();
        jMenuItemCadUser = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemRelPaciente = new javax.swing.JMenuItem();
        jMenuItemRelEnfer = new javax.swing.JMenuItem();
        jMenuItemRelMedicos = new javax.swing.JMenuItem();
        jMenuItemRelConsultas = new javax.swing.JMenuItem();
        jMenuItemRelAgenda = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTBVindo = new javax.swing.JMenuItem();
        jMenuItemAgenda = new javax.swing.JMenuItem();
        jMenuItemAgendamentos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        timer1.setDelay(10000L);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clínica Médica");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setTitle("Bem Vindo ");
        jInternalFrameBemVindo.setFocusTraversalPolicyProvider(true);
        try {
            jInternalFrameBemVindo.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInternal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCadPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1472110932_Person_CoffeeBreak_Male_Light.png"))); // NOI18N
        jButtonCadPaciente.setText(" ");
        jButtonCadPaciente.setToolTipText("Cadastro de Pacientes");
        jButtonCadPaciente.setMaximumSize(new java.awt.Dimension(125, 125));
        jButtonCadPaciente.setOpaque(false);
        jButtonCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadPacienteActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 110, 140));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setText("Cadastros ");
        jPanelInternal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 20));

        jButtonCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1472107157_people.png"))); // NOI18N
        jButtonCadUsuario.setToolTipText("Cadastro de Usuários / Funcionários");
        jButtonCadUsuario.setOpaque(false);
        jButtonCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsuarioActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 110, 140));

        jButtonCadEnfermeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1472111189_nurse_64.png"))); // NOI18N
        jButtonCadEnfermeira.setText(" ");
        jButtonCadEnfermeira.setToolTipText("Cadastro de Enfermeiras");
        jButtonCadEnfermeira.setOpaque(false);
        jButtonCadEnfermeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadEnfermeiraActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadEnfermeira, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 110, 140));

        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Agenda.png"))); // NOI18N
        jButtonAgenda.setText(" ");
        jButtonAgenda.setToolTipText("Novo Agendamento");
        jButtonAgenda.setOpaque(false);
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, 130));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setText("Agendamentos ");
        jPanelInternal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, 20));

        jButtonCadMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1472110863_Nurse_Male_Light.png"))); // NOI18N
        jButtonCadMedicos.setText(" ");
        jButtonCadMedicos.setToolTipText("Cadastro de Médicos");
        jButtonCadMedicos.setOpaque(false);
        jButtonCadMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedicosActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 140));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("Agendamento do Dia");
        jPanelInternal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1472107791_add-address.png"))); // NOI18N
        jButton1.setToolTipText("Agendamentos de Hoje");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 130, 130));

        jLabelPlanoFundPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/internalframe.png"))); // NOI18N
        jLabelPlanoFundPainel.setText(" ");
        jPanelInternal.add(jLabelPlanoFundPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1230, 560));

        jInternalFrameBemVindo.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(0, 40, 1250, 570);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de :");
        jInternalFrameBemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 220, 30);

        jButtonExitB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/exitb.png"))); // NOI18N
        jButtonExitB.setToolTipText("Sair da Tela Bem Vindo");
        jButtonExitB.setBorder(null);
        jButtonExitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitBActionPerformed(evt);
            }
        });
        jInternalFrameBemVindo.getContentPane().add(jButtonExitB);
        jButtonExitB.setBounds(1210, 0, 40, 40);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(90, 20, 1270, 640);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/if_group_46804.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 720, 60, 30);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabelUsuario.setToolTipText("Usuário Logado no Sistema");
        jLabelUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(70, 720, 140, 30);

        jLabelDataAtual.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabelDataAtual.setToolTipText("Data Atual");
        jLabelDataAtual.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabelDataAtual.setOpaque(true);
        getContentPane().add(jLabelDataAtual);
        jLabelDataAtual.setBounds(1000, 720, 180, 30);

        jLabelHoraAtual.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabelHoraAtual.setToolTipText("Horário Atual");
        jLabelHoraAtual.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabelHoraAtual.setOpaque(true);
        getContentPane().add(jLabelHoraAtual);
        jLabelHoraAtual.setBounds(1190, 720, 170, 30);

        jLabelDB.setToolTipText("Status do Banco de Dados");
        getContentPane().add(jLabelDB);
        jLabelDB.setBounds(620, 710, 50, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(660, 330, 600, 310);

        jLabelFundoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo_telaprincipal.jpg"))); // NOI18N
        jLabelFundoTelaPrincipal.setText(" ");
        jLabelFundoTelaPrincipal.setMaximumSize(new java.awt.Dimension(1307, 1200));
        jLabelFundoTelaPrincipal.setMinimumSize(new java.awt.Dimension(1307, 1200));
        jLabelFundoTelaPrincipal.setName(""); // NOI18N
        jLabelFundoTelaPrincipal.setPreferredSize(new java.awt.Dimension(1307, 1200));
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(-20, -40, 2800, 1250);

        jMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bookadd.png"))); // NOI18N
        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jMenuItemCadMed.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadMed.setText("Médicos");
        jMenuItemCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMedActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadMed);

        jMenuItemCadPac.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadPac.setText("Pacientes");
        jMenuItemCadPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadPacActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadPac);

        jMenuItemCadEnf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadEnf.setText("Enfermeiras");
        jMenuItemCadEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadEnfActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadEnf);

        jMenuItemCadUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadUser.setText("Usuários");
        jMenuItemCadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUserActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadUser);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reladd.png"))); // NOI18N
        jMenuRelatorios.setText("Relatórios");

        jMenuItemRelPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRelPaciente.setText("Pacientes");
        jMenuItemRelPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelPacienteActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelPaciente);

        jMenuItemRelEnfer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRelEnfer.setText("Enfermeiros");
        jMenuRelatorios.add(jMenuItemRelEnfer);

        jMenuItemRelMedicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRelMedicos.setText("Médicos");
        jMenuRelatorios.add(jMenuItemRelMedicos);

        jMenuItemRelConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRelConsultas.setText("Consultas");
        jMenuRelatorios.add(jMenuItemRelConsultas);

        jMenuItemRelAgenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRelAgenda.setText("Agendamentos");
        jMenuRelatorios.add(jMenuItemRelAgenda);

        jMenuBar1.add(jMenuRelatorios);

        jMenuFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/tools.png"))); // NOI18N
        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTBVindo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTBVindo.setText("Tela Bem Vindo");
        jMenuItemTBVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTBVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTBVindo);

        jMenuItemAgenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAgenda.setText("Agendamentos");
        jMenuItemAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendaActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemAgenda);

        jMenuItemAgendamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAgendamentos.setText("Agenda do Dia");
        jMenuItemAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendamentosActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemAgendamentos);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Atendimento Médico");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItem1);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/exitb.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1389, 829));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadEnfActionPerformed
        FormEnfermeiros tela = new FormEnfermeiros();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadEnfActionPerformed

    private void jButtonExitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitBActionPerformed
        // Comando para o Botão Sair da  Tela de Be Vindo!
        jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonExitBActionPerformed

    private void jMenuItemTBVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTBVindoActionPerformed
        jInternalFrameBemVindo.setVisible(true);
       
    }//GEN-LAST:event_jMenuItemTBVindoActionPerformed

    private void jMenuItemCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMedActionPerformed
        
        try {
            conex.executaSql("select *from usuarios where nome_usuario='"+ jLabelUsuario.getText()+"'");
            conex.rs.first();
            if(conex.rs.getString("tipo").equals("Administrador")){
             if(telamedicos == null){
                 telamedicos = new FormMedicos();
                 telamedicos.setVisible(true);
                 telamedicos.setResizable(false);
             }else{
                 telamedicos.setVisible(true);
                 telamedicos.setResizable(false);  }
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não tem permissão para esse acesso! \n"
                        + "Favor contate o Administrador do Sistema!");
            }
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Sem acesso de Administrador!"+ex);
}       

    }//GEN-LAST:event_jMenuItemCadMedActionPerformed

    private void jButtonCadMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedicosActionPerformed
       try {
            conex.executaSql("select *from usuarios where nome_usuario='"+ jLabelUsuario.getText()+"'");
            conex.rs.first();
            if(conex.rs.getString("tipo").equals("Administrador")){
             if(telamedicos==null){
                 telamedicos = new FormMedicos();
                 telamedicos.setVisible(true);
                 telamedicos.setResizable(false);
             }else{
                 telamedicos.setVisible(true);
                 telamedicos.setResizable(false);  }
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não tem permissão para esse acesso! \n"
                        + "Favor contate o Administrador do Sistema!");
            }
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Sem acesso de Administrador!"+ex);
}       

    
    }//GEN-LAST:event_jButtonCadMedicosActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed

    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Sair do Sistema?");
        if(resposta==JOptionPane.YES_OPTION){
        System.exit(0);}
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jButtonCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsuarioActionPerformed
        try {
            conex.executaSql("select *from usuarios where nome_usuario='"+ jLabelUsuario.getText()+"'");
            conex.rs.first();
            if(conex.rs.getString("tipo").equals("Administrador")){
              if(telausuarios==null){
                 telausuarios = new FormUsuarios();
                 telausuarios.setVisible(true);
                 telausuarios.setResizable(false);
             }else{
                 telausuarios.setVisible(true);
                 telausuarios.setResizable(false);  }   
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não tem permissão para esse acesso! \n"
                        + "Favor contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Sem acesso de Administrador!"+ex);
        }
    }//GEN-LAST:event_jButtonCadUsuarioActionPerformed

    private void jMenuItemCadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUserActionPerformed
         try {
            conex.executaSql("select *from usuarios where nome_usuario='"+ jLabelUsuario.getText()+"'");
            conex.rs.first();
            if(conex.rs.getString("tipo").equals("Administrador")){
              if(telausuarios==null){
                 telausuarios = new FormUsuarios();
                 telausuarios.setVisible(true);
                 telausuarios.setResizable(false);
             }else{
                 telausuarios.setVisible(true);
                 telausuarios.setResizable(false);  }   
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não tem permissão para esse acesso! \n"
                        + "Favor contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Sem acesso de Administrador!"+ex);
        }
    }//GEN-LAST:event_jMenuItemCadUserActionPerformed

    private void jButtonCadEnfermeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadEnfermeiraActionPerformed
        FormEnfermeiros tela = new FormEnfermeiros();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadEnfermeiraActionPerformed

    private void jButtonCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadPacienteActionPerformed
        FormPacientes tela = new FormPacientes();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadPacienteActionPerformed

    private void jMenuItemCadPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadPacActionPerformed
        FormPacientes tela = new FormPacientes();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadPacActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
       FormAgendamentos tela = new FormAgendamentos();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jMenuItemAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendaActionPerformed
        FormAgendamentos tela = new FormAgendamentos();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemAgendaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormAgendaDia tela = new FormAgendaDia();
        tela.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendamentosActionPerformed
        FormAgendaDia tela = new FormAgendaDia();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemAgendamentosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormAgendaMedico tela = new FormAgendaMedico();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemRelPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelPacienteActionPerformed
        Connection con = ConexaoDB.getConnection();

        //Esse método chama o nosso relatório Pacientes
        //Esse método pergunta se a pessoa quer imprimir o relatório
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a Impressão do Relatório?", "Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
        
            //Imprimindo o Relatório
            String src = "D:/Relatórios/Pacientes/Pacientes.jasper";
            
            JasperPrint jasperPrint = null;
            
            try {
                jasperPrint = JasperFillManager.fillReport(src, null, con);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane,"Erro ao Gerar o Relatório! \n" + ex);
            }
        JasperViewer view = new  JasperViewer(jasperPrint, false);
        view.setVisible(true);
        }
        

        
    }//GEN-LAST:event_jMenuItemRelPacienteActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Chama a conexão assim que inicia a tela.
        
    }//GEN-LAST:event_formWindowActivated

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // Thred que atualiza o horário
        //A linha Abaixo exibe a Hora Atual do Sistema
       Hora mostra_hora = new Hora();
       mostra_hora.ler_hora();
       jLabelHoraAtual.setText("Hora Atual: " + mostra_hora.hora);
    }//GEN-LAST:event_timer1OnTime

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonCadEnfermeira;
    private javax.swing.JButton jButtonCadMedicos;
    private javax.swing.JButton jButtonCadPaciente;
    private javax.swing.JButton jButtonCadUsuario;
    private javax.swing.JButton jButtonExitB;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDB;
    private javax.swing.JLabel jLabelDataAtual;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    private javax.swing.JLabel jLabelHoraAtual;
    private javax.swing.JLabel jLabelPlanoFundPainel;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAgenda;
    private javax.swing.JMenuItem jMenuItemAgendamentos;
    private javax.swing.JMenuItem jMenuItemCadEnf;
    private javax.swing.JMenuItem jMenuItemCadMed;
    private javax.swing.JMenuItem jMenuItemCadPac;
    private javax.swing.JMenuItem jMenuItemCadUser;
    private javax.swing.JMenuItem jMenuItemRelAgenda;
    private javax.swing.JMenuItem jMenuItemRelConsultas;
    private javax.swing.JMenuItem jMenuItemRelEnfer;
    private javax.swing.JMenuItem jMenuItemRelMedicos;
    private javax.swing.JMenuItem jMenuItemRelPaciente;
    private javax.swing.JMenuItem jMenuItemTBVindo;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternal;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables

}
