/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modeloConection.ConexaoDB;

/**
 *
 * @author Denis
 */
public class TelaLogin extends javax.swing.JFrame {

   ConexaoDB con = new ConexaoDB();
   
    public TelaLogin() {
        initComponents();
        
        URL caminhoIcone = getClass().getResource("/Imagens/icon.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        
        getRootPane().setDefaultButton(jButtonAcessar);
        con.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jButtonAcessar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelConnect = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login de Usuário");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(280, 50, 120, 30);

        jPasswordFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(280, 90, 120, 30);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelUsuario.setText("Usuário ");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(220, 50, 60, 30);

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelSenha.setText("Senha ");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(230, 90, 50, 30);

        jButtonAcessar.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButtonAcessar.setText("Acessar");
        jButtonAcessar.setOpaque(false);
        jButtonAcessar.setRolloverEnabled(true);
        jButtonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarActionPerformed(evt);
            }
        });
        jButtonAcessar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAcessarKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonAcessar);
        jButtonAcessar.setBounds(230, 140, 90, 30);

        jButtonSair.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.setOpaque(false);
        jButtonSair.setRolloverEnabled(true);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(330, 140, 90, 30);

        jLabelConnect.setFont(new java.awt.Font("Century725 Cn BT", 2, 14)); // NOI18N
        jLabelConnect.setText("DG  Softwares Developer Consultoria em TI & Desenvolvimento");
        getContentPane().add(jLabelConnect);
        jLabelConnect.setBounds(50, 190, 360, 30);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-aditivos-especiais-texteis-golden-01.png"))); // NOI18N
        jLabelLogo.setText(" ");
        jLabelLogo.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabelLogo.setMinimumSize(new java.awt.Dimension(60, 60));
        jLabelLogo.setPreferredSize(new java.awt.Dimension(55, 55));
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(-150, -50, 370, 380);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundotelaLogin.png"))); // NOI18N
        jLabelFundoLogin.setText(" ");
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(-40, 0, 510, 240);

        setSize(new java.awt.Dimension(458, 229));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarActionPerformed
       
       try{
           con.executaSql("select * from usuarios where nome_usuario= '"+jTextFieldUsuario.getText()+"'");
           con.rs.first();
           if(con.rs.getString("senha_usuario").equals(jPasswordFieldSenha.getText())){
               JOptionPane.showMessageDialog(rootPane,"Bem Vindo! " + jTextFieldUsuario.getText());
            TelaPrincipal tela = new TelaPrincipal(jTextFieldUsuario.getText());
            tela.setVisible(true);
            dispose();
        }else{
        JOptionPane.showMessageDialog(rootPane,"Problema com Usuário ou Senha! Tente novamente.");
        jTextFieldUsuario.requestFocus();
        jTextFieldUsuario.setText("");
        jPasswordFieldSenha.setText("");
           }
       }catch(SQLException ex){
         JOptionPane.showMessageDialog(rootPane,"Erro de Autenticação no Banco de Dados! \n Erro: " +ex);      
               }              
    }//GEN-LAST:event_jButtonAcessarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // Sair do Sistema por completo
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonAcessarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAcessarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAcessarKeyPressed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jPasswordFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaActionPerformed
     /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
     /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcessar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelConnect;
    private javax.swing.JLabel jLabelFundoLogin;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
